version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rest-catalog:
    build:
      context: ./rest-catalog
    container_name: iceberg-rest-catalog
    ports:
      - "8181:8181"
    depends_on:
      - minio
    volumes:
      - ./rest-catalog/config.yml:/config.yml
    entrypoint: ["java", "-jar", "iceberg-rest-catalog.jar", "server", "/config.yml"]

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    depends_on:
      - rest-catalog
    volumes:
      - ./trino/catalog:/etc/trino/catalog

  spark:
    image: docker.io/bitnami/spark:latest
    container_name: spark
    depends_on:
      - rest-catalog
    environment:
      - HOME=/tmp
      - SPARK_USER_HOME=/tmp
      - JAVA_TOOL_OPTIONS=-Duser.home=/tmp
      # Disable Hadoop security
      - HADOOP_SECURITY_AUTHENTICATION=simple
    volumes:
      - ./spark:/opt/spark-apps
      - ./users.csv:/opt/spark-apps/users.csv
    entrypoint: >
      /opt/bitnami/spark/bin/spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.4.2
      /opt/spark-apps/write_users_to_iceberg.py

volumes:
  minio_data: